spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqlmaster:3306/agilebpm?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 100861
    dbType: mysql
  activemq:
    broker-url: tcp://activemq:61616
    in-memory: false
    packages:
      trust-all: true
  redis:
    host: redisdb
    port: 6379
    password: 
    database: 9


logging:
  level:
    root: INFO
server:
  servlet:
    context-path: /

## security:
##  ignored:  [/agilebpm-ui/** ,/css/**, /js/**,/images/**,/webjars/**,/**/favicon.ico]
## /swagger-*,/v2/api-docs*,   swagger 免登陆

ab:
  jwt:
    enabled: false
  security:
    auth-ingores: /login.*,/agilebpm-ui*,/index.html,/swagger-*,/v2/api-docs*,
    csrf-ingores: a.feg.cn,127.0.0.1,localhost
  redis:
    use-redis-cache: false
  mail:
    mail-address: wuzhiping@qq.com
    nick-name: AgileBPM
    password: 
    send-host: sendmail
    send-port: 25
    ssl: false
  simple-mq:
    message-queue-type: synchronous


## 上传配置 db 存数据库 ，具体请看 IUploader 实现类
uploader:
  default: db
