version: '2'
services:
  ngx:
    image: nginx
    restart: always
    ports:
      - "85:80"
    links:
      - agilebpm
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./agilebpm-ui:/home/agilebpm-ui
      - ./bpm-app:/home/bpm-app
  mysqlmaster:
    image: mysql:5.7.15
    restart: always
    hostname: mysqlmaster
    environment:
      MYSQL_ROOT_PASSWORD: 100861
    volumes:
      - ./data/mysql-master:/var/lib/mysql/
      - ./config/mysql-master:/etc/mysql/conf.d/
    
  sendmail:
    image: shawoo/sendmail
    restart: always
    hostname: mail.feg.cn
    stdin_open: true
    tty: true
    
  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
      
  redisdb:
    image: redis
    restart: always
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    
  agilebpm:
    image: shawoo/agilebpm
    restart: always
    ports:
      - "8080:8080"
    #command: 
    volumes:
      #- ./agilebpm-spring-boot-samples-1.2.0-Beta.jar:/opt/agilebpm-base-spring-boot/agilebpm-spring-boot-samples/target/agilebpm-spring-boot-samples-1.2.1.jar
      - ./application.yml:/opt/agilebpm-base-spring-boot/agilebpm-spring-boot-samples/src/main/resources/application.yml
    environment:
      - ENV=dev
    depends_on:
      - redisdb
      - mysqlmaster
      - activemq
    links:
      - redisdb
      - mysqlmaster
      - activemq
      - sendmail
